semantic_mesh_pytorch3d/cameras.py
semantic_mesh_pytorch3d/config.py
semantic_mesh_pytorch3d/meshes.py

An important step is finding correspondences between the mesh and geo-referenced data such as polygons. Unfortunately, the mesh-to-image projections must be done in the arbitrary coordinate system defined by Metashape. Previously, I exported two meshes, one geospatial and one local, and used the hack that they had vertices in the same order. But now, I'm only using the local mesh and the local-to-EPGS:4978 transform contained in the cameras file.

Handle geo-referencing better

---

multiview_mapping_toolkit/meshes/meshes.py

This approach clusters the locations of the cameras to partition the mesh. Then it runs aggregation on each sub-region, which mitigates the issues with memory and runtime caused by trying to do aggregation on the whole mesh. These predictions are then combined into a texture for the full mesh. If the buffer is set sufficiently large such that no camera's predictions don't intersect with the cropped mesh, when they should have intersected with the full mesh, the results will be the same. 
This is functional but could be tested more.

Create chunked inference approach

---

README.md

Closes #80 . The README now includes info on how to find the environment's python path and how to change permissions to execute if they are denied after a user creates a new conda environment.

Added info about permissions to README

---

multiview_mapping_toolkit/constants.py
multiview_mapping_toolkit/meshes/meshes.py

This allows the mesh object to classify polygons based on the most common class, as predicted per-face, and weighted by face area. It currently only supports single-ID-per-face, but could be extended to take the distribution of ID predictions.
It could be accelerated by #82 , but I'd prefer to get it in before implementing that.

Classify polygons from face predictions

---

multiview_mapping_toolkit/cameras/cameras.py
multiview_mapping_toolkit/meshes/meshes.py

This enables the user to specify the `frustum_scale` in the jupyter notebooks. The size of the frustums shown in the mesh can be modified by changing the `frustum_scale` parameter.

Set frustum scale for metashape meshes

---

geograypher/cameras/cameras.py

Addressed the feedback on the previous merged PR #89. 
There was an issue where if there was only one camera and no frustum scale, the code would break. In this scenario, I decided to set the frustum_scale to 1. Would this be a good default value?

Fix one camera bug and clean up code

---

geograypher/meshes/meshes.py

When the `batch_size` is greater than 1, we extend the mesh so that the number of meshes is equal to `batch_size`, which is `batch_size` number of cameras. However, with this extension of meshes the indices of the mesh exceed the index for the number of faces which had caused an indexing error. To accommodate this we adjust the face indices considering the batch offset in the extended meshes.

Fixed out of index error for batching rendering operations

---

geograypher/meshes/meshes.py

The main improvement is first removing faces that are not contained by the target polygons, since this is a much faster operation than doing the overlay. This could yield slightly different results, since partially-overlapping faces are discarded. Therefore the heuristic of buffering the input polygon regions before selecting the subset of faces is used.

Accelerate labeling polygons from per-face labels

---

geograypher/cameras/cameras.py
geograypher/meshes/meshes.py

This pull request introduces disk-based caching for the `pix2face` computation. 
`cacher = ub.Cacher('pix2face', depends=[mesh_hash, camera_hash, render_img_scale])`
`ub.Cacher` provides on-disk caching so that the cache files persist across multiple Python instances. 
The cache generates unique keys for each combination of the dependencies (`mesh_hash`, `camera_hash`, `render_img_scale`). For each unique key generated the cache will create a cache file on disk. So if we have multiple combinations of `mesh_hash`, `camera_hash`, `render_img_scale`, there will be a specific cache file on disk for each combination. 
`pix2face = cacher.tryload(on_error='clear')`
`tryload` tries to load the cached data. If there’s an error loading, like data corruption, then the cache will clear its contents, …

Allow Caching for pix2face

---

.github/workflows/black.yml
.github/workflows/isort.yml
geograypher/cameras/cameras.py

The initial setup for the isort and black workflows was that isort would first run to completion and as soon as black detected that isort has finished execution black would begin to execute. This behavior was achieved using `workflow_run`, however, it resulted in unintended behavior on pull requests since `workflow_run` changes the state of `GITHUB_REF` to the default branch, which is main. So black was only running on the main branch regardless if it was triggered by a pull request.
Now, I am using workflow_call, which indicates that a workflow can be called by another workflow. This mechanism sets `GITHUB_REF` to the same value as it was in the caller workflow. So now isort runs first and triggers black to run and black  runs on the active pull request branch since `GITHUB_REF` is the …

Trigger black workflow with `workflow_run`

---

README.md
docs/index.md

We've heard that the conceptual workflow can be a little overwhelming on the main page. Because of this, I moved it to the new docs site.

Move conceptual workflow from README to docs site

---

docs/cameras/cameras.md
docs/cameras/derived_cameras.md
docs/cameras/index.md
docs/cameras/segmentor.md
docs/meshes/derived_meshes.md
docs/meshes/index.md
docs/meshes/meshes.md
mkdocs.yml
pyproject.toml

I added the docstrings for all the mesh and camera files. I saw there were other files that have docstrings also but I wanted to get your feedback on the current layout before I added the rest of the docstrings. Let me know what you think about the current structure. And where to add the documentation for some of the less prominent functions with docstrings. 
In addition, I customized the UI slightly but there are more options we can configure and if we want more granular control over the UI, we can add our own CSS styling. 
If you want to run the site locally you may get an error about mkdocstrings, if so run `pip install ‘mkdocstrings[python]’` to specify we are generating docstrings for python. I'm also currently working on documenting all these commands. Otherwise, here are some …

Add auto generated docstring documentation

---

.github/workflows/gh-pages.yml

The deployment is failing [here](https://github.com/open-forest-observatory/geograypher/actions/runs/9784645594/job/27015978786#step:12:16). It looks like the `mkdocstrings` plugin wasn't installed properly so this was my attempt to fix it. It works locally on Windows.

Add pip install command for mkdocstrings

---

geograypher/entrypoints/project_detections.py
geograypher/predictors/derived_segmentors.py

Often, pre-image object detectors predict information such as the class of the object and an associated confidence. This data, as well as the image that the detection was produced from when these detections were projected into geospatial coordinates. This PR merges this data back in to the geospatial projections.

Export information associated with per-image detections to geospatial projections

---

geograypher/cameras/cameras.py
geograypher/cameras/derived_cameras.py
geograypher/utils/geometric.py

This uses the photogrammetry result to compute a pitch and yaw off-nadir. The first step is define four points in the camera coordinate system, representing the camera origin, and one unit forward, up, and right. Then, using matrix operations, these points are projected first into the world coordinate frame and then the earth-centered, earth-fixed frame (ECEF). From here, geospatial operations are used to convert from ECEF to the appropriate projected CRS for that location. Then the angle from horizonal is computed for both pitch and yaw.
Closes #148

Compute camera angle off-nadir

---

geograypher/cameras/derived_cameras.py
geograypher/entrypoints/orthomosaic_predictions.py
geograypher/predictors/ortho_segmentor.py

The existing entrypoint used an outdate interface that relied on the `OrthoSegmentor` class which has been since deprecated and converted to individual functions.

Update segmentor entrypoint and skip null tiles

---

geograypher/utils/visualization.py

Rendering an RGB textured mesh was having problems because this check wasn't in place

Rescale label image to float [0,1] in composite

---

geograypher/cameras/cameras.py
geograypher/utils/numeric.py
tests/test_numeric.py

This PR vectorizes ray distance computation from (1, 1) to (N, N). It comes with a pretty comprehensive set of tests, which is nice because the code is dense.
I would like to test this by running the bird triangulation example, but I wasn't sure how to 1) run it in Jupyterlab and 2) use my checked out version of this branch. Because of where the geograypher environment was set up it was always running out of David's geograypher checkout. Any ideas on that? If not I can dig deeper.

Vectorize ray intersections

---

geograypher/entrypoints/render_labels.py
geograypher/meshes/meshes.py

This PR adds an option to save renders as compressed TIF files since `.npy` files were very large. I have also retained the option to save out `.npy` files.

Support saving renders as TIF files

---

tests/test_derived_meshes.py

Adds a basic mesh rendering test. Here is the test mesh:
Render testing with pytorch3d has been commented out due to an active issue. This is what rendering with TexturedPhotogrammetryMesh (pyvista) looks like:
And this is what rendering with TexturedPhotogrammetryMeshPyTorch3dRendering (pytorch3d) looks like:

Add render test that pytorch3d is failing

---

geograypher/meshes/meshes.py

One option for how to provide the mesh texture is a string, specifying the name of a scalar associated with the mesh to use. In most cases with .ply data, this is just "RGB" and "normals", but other formats can encode arbitrary data. The issue was the lookup operation was expecting a string, but instead getting a `pathlib.Path` object when using an entrypoint.

Force pyvista texture key to be string
